Made App Size 24MB
VaibhavCodeClub/learn pull request #174
Opened 2024-06-08 19:11 UTC by Gaurav-Kushwaha-1225

- I have solved the issue https://github.com/VaibhavCodeClub/learn/issues/145
- How I resolved it.
    - Firstly, release app `app-release.apk` wasn't being compiled after running `flutter build apk` or `flutter build apk --release` command in the terminal. It was constantly giving below error.
```
BUILD FAILED in 8s
[!] Your project requires a newer version of the Kotlin Gradle plugin.
    Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then update project/android/build.gradle:
    ext.kotlin_version = '<latest-version>'
```
- 
    - Then, I saw a solution on StackOverFlow to delete the **android folder in the project directory** and run `flutter create .`
    - After that, `flutter build apk` or `flutter build apk --release` commands worked and gave an .apk file of 35 MB size
    - But, using `flutter build apk --split-per-abi` command also I got an .apk file of 28 MB size. I read about this command on this [StackOverFlow Page](https://stackoverflow.com/questions/49567065/how-to-optimize-the-flutter-app-size) **2nd Answer**.
    - Then, I reduced the size of some images in assets folders like `black.svg`, `onion.png`, etc
    - At last, I got an .apk file of size 24.8 MB. 
- Hope this resolved the Issue #145.

2024-06-10 04:14 UTC, K123Ritesh requested changes

2024-06-10 04:14 UTC, K123Ritesh commented on android/app/build.gradle
> -        applicationId "vdrs.sappu.lafk.learn"
why you changed package name man??

2024-06-10 04:14 UTC, K123Ritesh commented on android/app/build.gradle
> -        multiDexEnabled true
does multidex enabling really needed??

2024-06-10 04:14 UTC, K123Ritesh commented on android/app/src/main/AndroidManifest.xml
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android">
Why change in label??

2024-06-10 04:14 UTC, K123Ritesh commented on android/app/src/main/res/mipmap-hdpi/ic_launcher.png
Icon Changed Why??

2024-06-10 04:15 UTC, K123Ritesh commented
@sapatevaibhav  @Gaurav-Kushwaha-1225 changed icon app label and package name also this is needed or he did it by mistake ??

2024-06-10 15:20 UTC, Gaurav-Kushwaha-1225 commented
Hi @K123Ritesh,

In above mentioned comment, after running `flutter create .` after deleting the android folder, since the usual command for generating `app-release.apk` i.e. `flutter build apk` wasn't working, a new android folder was created which has default package name, default icon, etc.

But it appears shocking that even during testing the app after the default android folder was generated the app's icon didn't change and was the a\same as before.

Anyways, I will make sure this time and push further commits to resolve this matter.

Thank you.

2024-06-12 08:57 UTC, sapatevaibhav commented on android/app/build.gradle
> -        multiDexEnabled true
nope will remove it since app supports minSdk 21

2024-06-12 10:00 UTC, K123Ritesh approved these changes

2024-06-12 10:00 UTC, merged