Xkaper001/issue62
VaibhavCodeClub/learn pull request #83
Opened 2024-05-16 13:49 UTC by xkaper001

Fixes #62

2024-05-16 14:02 UTC, xkaper001 commented
Hey @sapatevaibhav I have completed the #62 issue please review this.
Here's a demo of the implementation :)

https://github.com/VaibhavCodeClub/learn/assets/71162979/4f59dd09-a329-4ff6-a580-8405a20eb8c6

2024-05-17 18:16 UTC, sapatevaibhav commented
Please resolve conflicts by fetching from latest

2024-05-18 05:25 UTC, K123Ritesh commented
@xkaper001  Please Resolve The Conflics First

2024-05-18 17:53 UTC, sapatevaibhav commented
Hello @xkaper001 as new merges are causing merge conflicts please fetch it as well add please quizzes page in explore page.

2024-05-18 17:58 UTC, K123Ritesh requested changes

2024-05-18 17:58 UTC, K123Ritesh commented on lib/pages/modules/colours.dart
Minor Chage @xkaper001  change the color spelling

2024-05-18 19:31 UTC, xkaper001 commented
> Hello @xkaper001 as new merges are causing merge conflicts please fetch it as well add please quizzes page in explore page. 

Okay @sapatevaibhav will do that

2024-05-18 19:37 UTC, xkaper001 commented on lib/pages/modules/colours.dart
Hi @K123Ritesh , It was purposely kept that way to avoid misinterpretation with flutter `Colors`

2024-05-18 19:58 UTC, K123Ritesh commented on lib/pages/modules/colours.dart
Ok

2024-05-19 08:30 UTC, K123Ritesh approved these changes

2024-05-19 08:30 UTC, merged

2024-05-19 11:10 UTC, xkaper001 commented
This PR already solves the newly created issue #97